### ISSUE TITLE
Rspec might be unzipping the gzipped HTTP request body but not changing the encoding

### ISSUE THREAD

**Issue by marisveide** [rspec/rspec-metagem#28]
Hi!

I am trying to find which gem is unzipping the gzipped HTTP response body (as described here https://github.com/trusche/httplog/issues/58 and here https://github.com/google/google-api-ruby-client/issues/661#issuecomment-382974841), and have found that this happens only when running it from the rspec test.

So wanted to ask if that might be the case?
Basically, what's happening, is that when sending request to Google Cloud API, the response should come as gzipped body, but the httplog gets the body already unzipped, but with the encoding of the gzip. So it tries to unzip it again and fails.

Is rspec unzipping gzipped body? If yes, can it also change the encoding to not be the gzip?

Thanks!

Maris

**Comment by myronmarston** [comment]
RSpec has no code related to gzip whatsoever.  There must be something else doing that.
