### ISSUE TITLE
Suggestion: Warn / opt-in for remote database

### ISSUE THREAD

**Issue by jcutrell** [rspec/rspec-metagem#31]
Hi folks!

We just ran into a hiccup during our normal course of dev.

We accidentally had our environment set to production, with all production env vars active locally. Then, we ran our tests.

(Imagine the hilarity and sadness that ensued.)

We didn't know what happened for a few hours. All of this to say - perhaps it's a useful idea to have RSpec provide a warning or require explicit opt-in when being run in production environments, and/or when connecting to a remote data source? This may help others avoid mass deletion of data. (Of course, we have a backup, but not everyone will have an up-to-date backup.)

Yes, this is something we should be responsible for - but it seems like an overly powerful command to run a test suite and accidentally totally destroy a production database.

Note - I apologize if there is already a blocking/safety feature like this, or a previous thread addressing the issue; I couldn't find one in my cursory search. Thanks!

**Comment by myronmarston** [comment]
RSpec has no code that deals with databases whatsoever.  Different projects use different DBs (MySQL, Mongo, Redis, ...) and different libraries to access those DBs (Sequel, ROM, ActiveRecord).  As such, there's no way for RSpec to implement this unless we start providing integration in RSpec with all the different DBs and libraries.  We're not going to do that.

This is a reasonable request for a library that integrates RSpec with the specific ORM you are using.  If you're using ActiveRecord this is probably https://github.com/rspec/rspec-rails and you can open the feature request there.

**Comment by JonRowe** [comment]
It's worth noting that `rspec-rails` generates this in `spec/rails_helper.rb` by default in [lib/generators/rspec/install/templates/spec/rails_helper.rb](https://github.com/rspec/rspec-rails/blob/de6d35a90e2fb79ce7bb23f762fe1e7d6e66d9d2/lib/generators/rspec/install/templates/spec/rails_helper.rb):

```
abort("The Rails environment is running in production mode!") if Rails.env.production?
```

But `rspec-core` has no notion of needing to be for a web framework, so there is no "ideal" way to generate such a statement that will work, but could consider adding:

```
# # If using RSpec in a web environment, uncomment to prevent running tests in production
# abort("The rack environment is set to production") if ENV["RACK_ENV"] == "production"
```
