### ISSUE TITLE
[HELP] Filter warnings

### ISSUE THREAD

**Issue by djberg96** [rspec/rspec-metagem#38]
Is there a way to filter warnings from specific rubygems? I see you can filter them for backtraces, but it doesn't seem to apply to warnings.

The problem is that there are too many 3rd party libs that I don't have any control over, and they can literally cause Travis to bomb.

**Comment by JonRowe** [comment]
:wave: I'm afraid warning output is from Ruby, a quick google found this, https://github.com/jeremyevans/ruby-warning maybe give it a go?

This is also a meta repo for bringing other gems together.

**Comment by djberg96** [comment]
@JonRowe ~~Did I do something wrong?~~ Nm, just saw your answer, thought maybe I wasn't supposed to post here or something.

**Comment by JonRowe** [comment]
No! See comment above, this just isn't an RSpec issue (and even if it was this repo contains no code). :)
