### ISSUE TITLE
Expectation count in spec summary

### ISSUE THREAD

**Issue by christophweegen** [rspec/rspec-metagem#41]
Hello,

Minitest provides a nice statistic regarding number of passed assertions:

```
% ruby -Ilib:test test/minitest/test_minitest_test.rb
Run options: --seed 37685

# Running:

...................................................................... (etc)

Finished in 0.107130s, 1446.8403 runs/s, 2959.0217 assertions/s.

155 runs, 317 assertions, 0 failures, 0 errors, 0 skips
```
here I'm referring to `317 assertions`.

is there an analogue way in RSpec to show the number of passed expectations?

Thanks!

**Comment by JonRowe** [comment]
We don't currently, but it has been suggested before over in rspec/rspec#4 I'm closing this as a duplicate at that, but I welcome further discussion over on that issue!
