### ISSUE TITLE
Mismatch in released rspec and rspec-core versions

### ISSUE THREAD

**Issue by vishuvig** [rspec/rspec-metagem#49]
Hi,

As part of our build process, we have a few different gems that install `rspec` and `rspec-core` (both at the latest versions). We are now running in to an issue as a new version of `rspec-core` was released earlier today (which in itself is fine) but due to the runtime dependencies of `rspec` (defined [here](https://github.com/rspec/rspec/blob/master/rspec.gemspec#L42)), we are no longer able to run any builds.

As `rspec` v3.8.0 (currently the latest) depends on `rspec-core`, `rspec-expectations` and `rspec-mocks` v3.8.0 (which are no longer the latest).

I do see a commit in `rspec` to push to v3.9.0 [here](https://github.com/rspec/rspec/blob/3-9-maintenance/lib/rspec/version.rb#L3); would it be possible to publish the new version of the gem? If not, please advise of a way we can work around this dependency issue.

Thanks!

**Comment by JonRowe** [comment]
@vishuvig yes the release was in progress, I'm a bit confused as to how this broke your build though, if you use `gem 'rspec', '~> 3.8'` it would have just worked for example.

**Comment by marek-knappe** [comment]
> @vishuvig yes the release was in progress, I'm a bit confused as to how this broke your build though, if you use `gem 'rspec', '~> 3.8'` it would have just worked for example.

I had the same problem - and the problem was with serverspec and busser-serverspec - it doesn't specify the version so gem install serverspec installed 3.9 (as it didn't include metapackage, just rspec-core) and busser-serverspec installed metapackage rspec with 3.8

Thanks for checking though

**Comment by JonRowe** [comment]
Bundler should have worked that out, sounds like there could be an issue with its resolution, I was delaying releasing the meta package until all of the other gems were out and released and I was having difficulties with nokogiri to allow me to release rspec-rails :joy:
