### ISSUE TITLE
https://relishapp.com/rspec can not open

### ISSUE THREAD

**Issue by tianlu1677** [rspec/rspec-metagem#70]
[https://relishapp.com/rspec](https://relishapp.com/rspec)

**Comment by pirj** [comment]
```
Why this domain has been suspended

Email address has not been verified.
This is a new domain registration and the Registrant email address has not been verified.

or

The Registrant contact data for this domain was modified but still requires verification.
Specifically the First Name, Last Name and/or email address have been changed and never verified.
```
This is quite sad.
cc @JonRowe

**Comment by pirj** [comment]
> Relish is closing down.
> We are no longer accepting sign-ups for Relish.
> Please [join us on our new adventure, Cucumber Pro](https://cucumber.io/pro)

https://cucumber.io works

**Comment by pirj** [comment]
Related ticket https://github.com/rspec/rspec-dev/issues/199

**Comment by pirj** [comment]
Fixed by Relishapp
