### ISSUE TITLE
APPLICATION ERROR 🔴🔴🔴❗❗❗❗

### ISSUE THREAD

**Issue by PowerLevel9000** [rspec/rspec-metagem#72]
![image](https://github.com/rspec/rspec-metagem/assets/116451144/1a83fd84-7329-4eca-b0c0-ef8497769fde)

# GEM PAGE documentation isuue

Page is not visible on gem docs

**Comment by JonRowe** [comment]
RSpec does not host anything on Heroku, if this is relishapp, that service (not controlled by us) was shutdown. There are docs at https://rspec.info/documentation including replacement "feature" documentation e.g. https://rspec.info/features/3-12/rspec-core/
